# Generated by Django 5.1.7 on 2025-03-16 17:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0005_alter_mailing_finish_send_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='finish_send_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 17, 20, 44, 19, 120756), verbose_name='Дата и время окончания отправки'),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='first_send_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 16, 20, 44, 19, 120734), verbose_name='Дата и время первой отправки'),
        ),
    ]
