# Generated by Django 5.1.7 on 2025-03-18 07:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0007_alter_mailing_finish_send_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='finish_send_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 19, 10, 17, 32, 905596), verbose_name='Дата и время окончания отправки'),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='first_send_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 18, 10, 17, 32, 905571), verbose_name='Дата и время первой отправки'),
        ),
    ]
